root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  delay = 5000
  bin = "bin/api"
  full_bin = ""
  include_ext = ["go", "tmpl", "templ", "html"]
  exclude_dir = ["bin", "node_modules", "tmp"]
  exclude_regex = ["_templ.go"]

[color]
  enabled = true

[log]
  time = true

[screen]
  clear_on_rebuild = false