# Dockerfile.dev
FROM golang:1.24.3

# Install build dependencies for CGO (if necessary for sqlite)
RUN apt-get update && apt-get install -y gcc libc6-dev
RUN apt update && apt install -y nodejs npm

WORKDIR /app

# Zkopírujeme go.mod a go.sum a stáhneme dependencies (cache)
COPY go.mod go.sum ./
RUN go mod download

# Nainstalujeme air pro live reload
RUN go install github.com/air-verse/air@latest

# Zkopírujeme všechny zdroje
COPY . .

# Nainstalujeme node dependencies (tailwind)
RUN npm install

# Vystavíme port z .env (default 3000)
ENV PORT=3000

# Spustíme air
CMD ["air"]