services:
  app:
    build: .
    container_name: RustDeskServer
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./db:/app/db
      - ./certs:/app/certs
    ports:
      - "${PORT:-3000}:3000"
